name=input("What is your name?")
print("Welcome to python basic calculator, ", name, "!")
number1=input("please enter an integer number : ")
number2=input("please enter another integer number : ")
number1=int(number1)
number2=int(number2)
print("sum of the two numbers are, ", number1+number2)
print("Subtraction of those numbers are, ", number1-number2)
print("multiplication of those two nubmers are, ", number1*number2)
print("division of those two numbers is : ", number1/number2)
print("modulus of those numbers are :", number1%number2)
print("square of those two numbers is : ", number1**2 ,"," ,number2**2)
print("division of those number without any float number is : ", number1//number2)